; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32dev]
platform = espressif32
board = nodemcu-32s ; ou ton modèle exact
framework = arduino
monitor_speed = 115200
monitor_port = COM3

lib_deps = 
    lvgl/lvgl@^9.0.0
    lovyan03/LovyanGFX@^1.2.19
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^6.21.3

build_flags =
    -D LV_CONF_SKIP              ; On saute le fichier lv_conf.h
    -D LV_COLOR_DEPTH=16        ; 16 bits pour l'écran
    -D LV_MEM_SIZE=64000U       ; Allocation de la RAM pour LVGL 
    -D LV_TICK_CUSTOM=1         ; Gestion auto du temps (très important)
    -D LV_USE_LOG=1             ; Pour voir si ça plante dans le moniteur
    -D LV_FONT_MONTSERRAT_10=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_24=1

board_build.partitions = huge_app.csv